describe('Final Homework - Automation Testing (Ganna Andrushchenko)', () => {
    
    it('Confirmation of Transaction Success after Deposit and Withdrawal',() => {
        cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
        cy.title().should('eq','XYZ Bank')
        //cy.get('button[ng-click="customer()"]').click()
        cy.get('button[ng-click="customer()"]').invoke('removeAttr','target').click()
        cy.url().should('include','https://www.globalsqa.com/angularJs-protractor/BankingProject/#/customer')
        //cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/customer')
        cy.get('select[name="userSelect"]').select('Harry Potter')
        //cy.get('button[type="submit"]').click()
        cy.get('button[type="submit"]').invoke('removeAttr','target').click()
        cy.url().should('include','https://www.globalsqa.com/angularJs-protractor/BankingProject/#/account')
        //cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/account')
        cy.get('span[class="fontBig ng-binding"]').should('have.text', 'Harry Potter')
        cy.get('strong[class="ng-binding"]').contains('Dollar').should('have.text', 'Dollar')
        cy.get('button[ng-class="btnClass2"]').click()
        cy.get('input[type="number"]').type('77')
        cy.get('button[type="submit"]').click()
        cy.get('span[ng-show="message"]').should('have.text','Deposit Successful')
        //cy.get('button[ng-class="btnClass1"]').click()
        cy.get('button[ng-class="btnClass1"]').invoke('removeAttr','target').click()
        cy.url().should('include','https://www.globalsqa.com/angularJs-protractor/BankingProject/#/listTx')
        //cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/listTx')
        cy.get('table[class="table table-bordered table-striped"] tbody tr:nth-child(1) td:nth-child(2)').contains('77')
        cy.get('table[class="table table-bordered table-striped"] tbody tr:nth-child(1) td:nth-child(3)').contains('Credit')
        //cy.get('button[ng-click="back()"]').click()
        cy.get('button[ng-click="back()"]').invoke('removeAttr','target').click()
        cy.url().should('include','https://www.globalsqa.com/angularJs-protractor/BankingProject/#/account')
        //cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/account')
        cy.get('button[ng-click="withdrawl()"]').click()
        cy.get('input[ng-model="amount"]').type('77')
        cy.get('button[type="submit"]').click()
        cy.get('span[ng-show="message"]').should('have.text','Transaction successful')
        //cy.get('button[ng-class="btnClass1"]').click()
        cy.get('button[ng-class="btnClass1"]').invoke('removeAttr','target').click()
        //cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/listTx')
        cy.url().should('include','https://www.globalsqa.com/angularJs-protractor/BankingProject/#/listTx')
        //cy.wait(3000)
        cy.get('table[class="table table-bordered table-striped"] tbody tr:nth-child(2) td:nth-child(3)').contains('Debit')
})

})